import { CheckCircle2, Mail, Phone } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { business, mailHref, telHref } from '../config/business';
import { track } from '../lib/analytics';

type State='idle'|'opening';

export function QuoteForm() {
  const [state,setState]=useState<State>('idle');
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const name=String(form.get('name')||'');const phone=String(form.get('phone')||'');const suburb=String(form.get('suburb')||'');const service=String(form.get('service')||'');const message=String(form.get('message')||'');const subject=encodeURIComponent(`Website quote request — ${name||'New enquiry'}`);const body=encodeURIComponent(`Name: ${name}\nPhone: ${phone}\nSuburb: ${suburb}\nService: ${service}\n\nJob details:\n${message}`);track('quote_submit',{source:'website'});setState('opening');window.location.href=`${mailHref}?subject=${subject}&body=${body}`;window.setTimeout(()=>setState('idle'),1500);};
  return <section className="quote-section" id="quote"><div className="quote-backdrop" aria-hidden="true"/><div className="container quote-grid"><div className="quote-copy"><div className="eyebrow">REQUEST A QUOTE</div><div className="gold-rule"/><h2>Tell us what needs fixing.</h2><p>Send the basics and your phone will open a pre-filled email to JDC. For urgent work, calling is faster.</p><div className="direct-contact"><a href={telHref} onClick={()=>track('phone_click',{location:'quote'})}><Phone/><div><span>CALL</span><strong>{business.phoneDisplay}</strong></div></a><a href={mailHref} onClick={()=>track('email_click',{location:'quote'})}><Mail/><div><span>EMAIL</span><strong>{business.email}</strong></div></a></div><ul className="quote-checks"><li><CheckCircle2/> Clear scope</li><li><CheckCircle2/> Upfront pricing</li><li><CheckCircle2/> Brisbane &amp; SEQ</li></ul></div><form className="quote-form" onSubmit={submit}><div className="form-row"><label>Name<input name="name" autoComplete="name" required/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required/></label></div><div className="form-row"><label>Suburb<input name="suburb" autoComplete="address-level2" required/></label><label>Service<select name="service" defaultValue=""><option value="" disabled>Select a service</option><option>Blocked drain</option><option>Leak / burst pipe</option><option>Hot water</option><option>Residential plumbing</option><option>Commercial maintenance</option><option>Gas fitting</option><option>Renovation / installation</option><option>Other</option></select></label></div><label>What needs doing?<textarea name="message" rows={5} placeholder="Describe the issue, access and anything already inspected." required/></label><button className="button button-gold form-submit" type="submit" disabled={state==='opening'}>{state==='opening'?'Opening email…':'Prepare quote request →'}</button><small>This version does not store form data. It hands the enquiry to your email app, avoiding a database and spam surface until direct lead capture is enabled.</small></form></div></section>;
}
